### ISSUE TITLE
ICTIO: Relax strict check of ICTIO_BASIC_XXXXXXXX.zip for ZIP file name

### ISSUE THREAD

**Issue by AlexAmoSfC** [eosc-cos4cloud/mecoda-orange#10]
Relax strict check of ICTIO_BASIC_XXXXXXXX.zip for ZIP file name

**Comment by AlexAmoSfC** [comment]
OK. Marking as PENDING_VALIDATION and self-assigning.

**Comment by pynomaly** [comment]
Solved in [fix/ictio_errors](https://github.com/eosc-cos4cloud/mecoda-orange/pull/12/commits/23f6fdd8f8551cfb79383a3338a92845ed8c4d73).

**Comment by AlexAmoSfC** [comment]
I'll keep the tag PENDING_VALIDATION so we can quickly enumerate things that we want the users to test in a technical review working session or similar. Thnaks Ana!
