### ISSUE TITLE
ICTIO: Enable direct load of uncompressed database files

### ISSUE THREAD

**Issue by AlexAmoSfC** [eosc-cos4cloud/mecoda-orange#11]
Enable the ICTIO widget to allow direct load load of the XLSX file containing a valid ICTIO database (typically, the `BDB_xxxxxx.xlsx` that can be found inside the `ICTIO_BASIC_XXXXXXXX.zip` file).

Don't rewrite code. You don't need to, since you can still rely on IctioPy lib for that task. In order to load an ICTIO XLSX file instead of an ICTIO ZIP, do the following:

```
dataframe = ictiopy.sanitizedb(ictiopy.load_ictio_bdb_file(path_to_folder_with_xlsx_file, name_of_xlsx_file_with_extension))
```
Using this code, the output will be exactly the same as usual.

After that, some help text messages will have to be modified. We can add this text just above the "NOTE":

> You can also specity an XLSX file if you have already extracted the file `BDB_XXXXXXXX.xlsx` that can be found inside `ICTIO_BASIC_XXXXXXXX.zip`

**Comment by pynomaly** [comment]
![ictio_widget_new](https://user-images.githubusercontent.com/59539934/172357579-f306f322-2cd7-41aa-82b6-8b4e55899db0.png)

Upload options for zip files and xlsx files. Solved in [fix: ictio upload xlsx](https://github.com/eosc-cos4cloud/mecoda-orange/commit/8a0534bb174435c2ded316c80ef7478f592378b8)
