### ISSUE TITLE
Smartcitizen API issue downloading data

### ISSUE THREAD

**Issue by d-prieto** [eosc-cos4cloud/mecoda-orange#38]
Hi there, while teaching I had problems when I was downloading the data with my students. 

We all downloaded this Monday and Tuesday (morning in Europe) data from the kit 15822 data from January for each second. 

Some of them got all the data (around 122 k rows) and some of them they had less data (around 1 500 rows).

**Comment by pynomaly** [comment]
Sorry, I hadn't seen your issue. The smartcitizen widget and API are made and maintained by Fablab and @oscgonfer Maybe he can give you an answer.

**Comment by oscgonfer** [comment]
Hi, is this still an issue? I believe this was solved since then (at least on my side).
