### ISSUE TITLE
ICTIO: Add year-month filter dialog

### ISSUE THREAD

**Issue by AlexAmoSfC** [eosc-cos4cloud/mecoda-orange#8]
Add date filters in ICTIO widget, similar to the ones implemented in the widgets for other Citizen Observatories like OdourCollect:

![image](https://user-images.githubusercontent.com/83209147/171316218-9e11942d-4f82-42ab-ab15-fa55006cb6cf.png)

**Comment by pynomaly** [comment]
Created `split_date` function to take the dataframe, create datetime column, split rows above init date and below end date. 

```
def split_date(observations, init, end):
    observations['obs_date'] = observations['obs_year'].astype(int).astype(str) + observations['obs_month'].astype(int).astype(str).str.zfill(2) + observations['obs_day'].astype(int).astype(str).str.zfill(2)
    observations['obs_date'] = pd.to_datetime(observations['obs_date'])
    observations = observations[observations['obs_date'] >= init]
    observations = observations[observations['obs_date'] <= end]
    observations = observations.drop(['obs_date'], axis=1)
    return observations
```
Init date is set to the min date in dataframe (1860-01-01) and end date is set to today, so if not changed gets the whole dataframe as a result:
![ictio_widget_new](https://user-images.githubusercontent.com/59539934/171371603-32bc8f65-60d5-4245-9293-1a9fbf800880.png)

**Comment by pynomaly** [comment]
Solved in [fix/ictio_errors](https://github.com/eosc-cos4cloud/mecoda-orange/pull/12/commits/23f6fdd8f8551cfb79383a3338a92845ed8c4d73). Tested in Virtual Machine.
