### ISSUE TITLE
ICTIO: Control excessive amount of values in certain features (move to meta) 

### ISSUE THREAD

**Issue by AlexAmoSfC** [eosc-cos4cloud/mecoda-orange#9]
Some of the "features" (columns) of Ictio's database shouldn't be treated as categorical type, since they consume too much memory and Orange tends to "freeze". After testing, we found out that Orange does not actually freeze, it just takes a lot of time minutes to process all data, and meanwhile it's not responsive, specially in Windows.

Instead, the problematic columns should be converted from categorical type to text type (that is, treated as metadata) in order to avoid resource issues. Based on Orange's autodetection capabilities, the columns that should be considered for being treated as metadata are:

- obd_id
- taxon_code
- scientific_name
- number_of_fish
- obs_comments
- user_id
- checklist_id
- port
- location_type
- watershed_code
- watershed_name

**Comment by pynomaly** [comment]
After removing column type change to categorical in string features, Orange Table set only 3 meta columns:
* obs_id
* obs_comments
* checklist_id

![ictio_widget_new2](https://user-images.githubusercontent.com/59539934/171374902-02e093a7-2c8b-4cc0-8c67-7fba41b5e9b7.png)

Performance should be lighter, needed further check in different windows devices required before closing the issue.

**Comment by pynomaly** [comment]
Performance at this point is good in amount of time to perform "Feature Statistics" or "Distribution" widgets using Virtual Machine. I don't have problems with any of the connections to other widgets. I understand Orange is choosing the more effective type for any feature not indicated by default. I will make more tests of performance with this structure and try to remove unnecessary or duplicated fields.

**Comment by AlexAmoSfC** [comment]
I will keep the PENDING_VALIDATION tag here as something to be validated by users.
Thanks for the great job
